/**
 * Typed client for the OceanSight FastAPI backend (backend/app/api/*).
 *
 * Offline fallback (docs/16 §6, docs/21 §2): if the backend is unreachable (network error or
 * timeout — NOT a typed 4xx/5xx), the client tries a bundled snapshot at
 * `/fallback/<fallbackKey(path)>.json`, generated by `scripts/snapshot_fallback.py` for the reference scenario
 * requests. Key format: path+query with every char outside [A-Za-z0-9._-] replaced by "_",
 * e.g. `/v1/grid/2023-05-11?depth=100` -> `v1_grid_2023-05-11_depth_100`. POST bodies are
 * appended as `__` + sorted "key_value" pairs of the flattened JSON body.
 */
export const API_URL = (process.env.NEXT_PUBLIC_API_URL || "http://localhost:8100").replace(/\/$/, "");

/**
 * Whether to try the live API at all. A deployed page with no configured API goes straight to the saved
 * copies instead of probing the visitor's own machine (localhost:8100).
 */
export function liveApiEnabled(): boolean {
  if (process.env.NEXT_PUBLIC_API_URL || typeof window === "undefined") return true;
  return ["localhost", "127.0.0.1", "[::1]"].includes(window.location.hostname);
}

export class ApiError extends Error {
  constructor(public status: number, public code: string, public detail: string) {
    super(detail);
  }
}

/** Message for a request with no live backend and no saved copy (ErrorState shows offline wording for it). */
export const OFFLINE_NO_COPY = "Offline copy not available for this selection.";

export type Fetched<T> = T & { __fallback?: boolean };

function flatten(obj: unknown, prefix = ""): string[] {
  if (obj === null || typeof obj !== "object") return [`${prefix}_${String(obj)}`];
  return Object.keys(obj as Record<string, unknown>)
    .sort()
    .flatMap((k) => flatten((obj as Record<string, unknown>)[k], prefix ? `${prefix}_${k}` : k));
}

export function fallbackKey(pathWithQuery: string, body?: unknown): string {
  let key = pathWithQuery.replace(/^\//, "");
  if (body !== undefined) key += "__" + flatten(body).join("_");
  return key.replace(/[^A-Za-z0-9._-]/g, "_");
}

async function tryFallback<T>(path: string, body?: unknown): Promise<Fetched<T> | null> {
  try {
    const r = await fetch(`/fallback/${fallbackKey(path, body)}.json`);
    if (!r.ok) return null;
    const data = (await r.json()) as T;
    return Object.assign(data as object, { __fallback: true }) as Fetched<T>;
  } catch {
    return null;
  }
}

async function request<T>(path: string, init?: RequestInit & { json?: unknown }, timeoutMs = 20000): Promise<Fetched<T>> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  let res: Response;
  try {
    if (!liveApiEnabled()) throw new Error("live API not configured");
    res = await fetch(`${API_URL}${path}`, {
      ...init,
      method: init?.json !== undefined ? "POST" : init?.method || "GET",
      headers: init?.json !== undefined ? { "Content-Type": "application/json" } : undefined,
      body: init?.json !== undefined ? JSON.stringify(init.json) : undefined,
      signal: ctrl.signal,
    });
  } catch {
    clearTimeout(timer);
    const fb = await tryFallback<T>(path, init?.json);
    if (fb) return fb;
    throw new ApiError(0, "backend_unreachable", OFFLINE_NO_COPY);
  }
  clearTimeout(timer);
  if (!res.ok) {
    let code = "http_error";
    let detail = `HTTP ${res.status}`;
    try {
      const j = await res.json();
      code = j.error || code;
      detail = j.detail || detail;
    } catch {}
    throw new ApiError(res.status, code, detail);
  }
  return (await res.json()) as Fetched<T>;
}

export const get = <T,>(path: string) => request<T>(path);
export const post = <T,>(path: string, json: unknown) => request<T>(path, { json });

/** Human, calm messages per error code (docs/12 error states, docs/21 §2). */
export function friendlyError(e: unknown): string {
  if (!(e instanceof ApiError)) return "Something went wrong loading this view.";
  switch (e.code) {
    case "on_land":
    case "out_of_domain":
      return "This point is on land or outside the study domain (5–30°N, 45–105°E).";
    case "date_out_of_range":
      return `No reconstruction for that date. ${e.detail}`;
    case "database_unavailable":
      return "The metadata database is temporarily unavailable — map and profiles still work.";
    case "data_unavailable":
    case "validation_unavailable":
    case "embedding_unavailable":
      return "This product has not been computed yet on the server.";
    case "region_too_large":
      return "Region too large — try a smaller area.";
    case "no_ocean_cells":
      return "The selected box contains no ocean cells.";
    case "backend_unreachable":
      return e.detail;
    default:
      return e.detail || "Unexpected error.";
  }
}

// ---------------------------------------------------------------- response types
export interface Meta {
  product: string;
  tagline?: string;
  domain: { min_lat: number; max_lat: number; min_lon: number; max_lon: number; resolution_deg: number };
  depths_m: number[];
  period: { start: string; end: string; n_days: number };
  splits: { train_years: number[]; val_years: number[]; test_years: number[] };
  production_model: string;
  models: Array<Record<string, unknown> & { name: string; architecture: string }>;
  available_models: string[];
  input_sources: Record<string, Record<string, string>>;
  target_source: Record<string, string>;
  data_label: string;
}

export interface GridResponse {
  date: string;
  requested_date: string;
  depth_m?: number;
  variable?: string;
  product?: string;
  units: string;
  grid: { lat: number[]; lon: number[]; values: (number | null)[][] };
  stats: { min: number; max: number; mean: number } | null;
  source: string;
  data_label: string;
  model_version: string;
  notice: string | null;
}

export interface ArgoFloatRef {
  id: number;
  platform_number: string;
  cycle_number: number;
  profile_date: string;
  lat: number;
  lon: number;
  distance_km: number;
  date_offset_days: number;
  split: string;
  independent: boolean;
  temperature_c_std_depths: (number | null)[];
}

export interface Derived {
  mld_m: number | null;
  d20_m: number | null;
  d26_m: number | null;
  tchp_kj_cm2: number | null;
}

export interface ProfileResponse {
  date: string;
  requested_date: string;
  lat: number;
  lon: number;
  cell: { lat: number; lon: number };
  depths_m: number[];
  temperature_c: (number | null)[];
  uncertainty_c: (number | null)[] | null;
  baseline_climatology_c: (number | null)[];
  comparisons: Record<string, (number | null)[]>;
  target_product_c: (number | null)[] | null;
  derived: Derived;
  nearest_argo_float: ArgoFloatRef | null;
  argo_lookup: string;
  data_label: string;
  model_version: string;
  notice: string | null;
}

export interface Headline {
  study_period: string;
  n_days_reconstructed: number;
  n_argo_profiles_total: number | null;
  target_days: number | null;
  n_models_compared: number;
  grid: string;
  production_model: string;
  validation: {
    held_out_period: string;
    n_independent_profiles: number;
    at_depths: { depth_m: number; rmse_c: number | null; climatology_rmse_c: number | null; n_obs: number | null }[];
    caveat: string;
  } | null;
}

export interface RegionStats {
  date: string;
  n_ocean_cells: number;
  mean_tchp_kj_cm2: number | null;
  max_tchp_kj_cm2: number | null;
  mean_mld_m: number | null;
  mean_d20_m: number | null;
  mean_d26_m: number | null;
  frac_cells_tchp_gt_50: number | null;
  mean_sst_c: number | null;
  mean_profile_c: (number | null)[];
  barrier_layer_flag: boolean | null;
  barrier_layer_proxy: { frac_cells_sss_below_threshold: number | null; sss_threshold_psu: number; note: string };
  notice: string | null;
}

export interface BBox {
  min_lat: number;
  max_lat: number;
  min_lon: number;
  max_lon: number;
}

export interface Region {
  name: string;
  bbox: BBox;
}

export interface DepthMetric {
  depth_m: number;
  n_obs: number;
  rmse_c?: number;
  bias_c?: number;
  corr?: number | null;
  clim_rmse_c?: number;
  skill_vs_climatology?: number;
  baseline_rmse_c?: number | null;
  lightgbm_rmse_c?: number | null;
  nosss_rmse_c?: number | null;
  target_product_rmse_c?: number | null;
}

export interface ValidationSummary {
  model: string;
  split: string;
  independent: boolean;
  held_out_period: string;
  n_profiles: number;
  per_depth: DepthMetric[];
  overall: Record<string, { mean_rmse_c: number | null; mean_bias_c: number | null; n_obs: number }>;
  uncertainty_calibration: {
    frac_within_1sigma: number | null;
    frac_within_2sigma: number | null;
    calibrated: { frac_within_1sigma?: number; frac_within_2sigma?: number; fit_on: string; note?: string } | null;
  };
  caveat: string;
  source: string;
}

export interface CycloneTrack {
  id: number;
  sid: string;
  name: string;
  season: number;
  peak_category: string | null;
  start: string | null;
  end: string | null;
  points: { time: string; lat: number; lon: number; category: string | null; grade: string | null; wind_kt: number | null }[];
}

export interface FuelResponse {
  id: number;
  name: string;
  season: number;
  peak_category: string | null;
  lead_days: number;
  points: {
    time: string;
    lat: number;
    lon: number;
    category: string | null;
    wind_kt: number | null;
    tchp_kj_cm2: number | null;
    d26_m: number | null;
    sst_c: number | null;
    ocean_date: string | null;
  }[];
  max_tchp_kj_cm2: number | null;
  note: string;
}

export interface ArgoMarker {
  id: number;
  platform_number: string;
  cycle_number: number;
  profile_date: string;
  lat: number;
  lon: number;
  split: string;
  independent: boolean;
  rmse_c: number | null;
}

export interface SectionResponse {
  date: string;
  lat: number;
  lon: number[];
  depths_m: number[];
  temperature_c: (number | null)[][];
  model_version: string;
  data_label: string;
}

/** GET /v1/section/{day} with orientation/variable (interactive vertical section). */
export interface SectionAnyResponse {
  date: string;
  requested_date: string;
  orientation: "zonal" | "meridional";
  variable: "temp" | "anomaly" | "uncertainty";
  units: string;
  x: number[];
  x_name: "lon" | "lat";
  depths_m: number[];
  values: (number | null)[][];
  lat: number | number[];
  lon: number | number[];
  model_version: string;
  data_label: string;
  notice: string | null;
}

/** GET /v1/timeline — reconstructed column at one cell through time (+ derived MLD/D20/D26). */
export interface TimelineResponse {
  lat: number;
  lon: number;
  cell: { lat: number; lon: number };
  start: string;
  end: string;
  requested_start: string;
  requested_end: string;
  stride_days: number;
  dates: string[];
  depths_m: number[];
  temperature_c: (number | null)[][]; // [depth][time]
  climatology_c: (number | null)[][] | null;
  mld_m: (number | null)[];
  d20_m: (number | null)[];
  d26_m: (number | null)[];
  max_samples: number;
  model_version: string;
  data_label: string;
  notice: string | null;
}
