/**
 * Typed client for the OceanSight FastAPI backend (backend/app/api/*).
 *
 * Offline fallback (docs/16 §6, docs/21 §2): if the backend is unreachable (network error or
 * timeout — NOT a typed 4xx/5xx), the client tries a bundled snapshot at
 * `/fallback/<fallbackKey(path)>.json`, generated by `scripts/snapshot_fallback.py` for the reference scenario
 * requests. Key format: path+query with every char outside [A-Za-z0-9._-] replaced by "_",
 * e.g. `/v1/grid/2023-05-11?depth=100` -> `v1_grid_2023-05-11_depth_100`. POST bodies are
 * appended as `__` + sorted "key_value" pairs of the flattened JSON body.
 *
 * Base URL: `NEXT_PUBLIC_API_URL` (inlined at build time). The localhost default applies to
 * `next dev` only; a production build without the variable has no API (`API_CONFIGURED` false):
 * data requests go straight to the bundled snapshots, and anything else fails with a clear
 * `api_not_configured` error instead of calling localhost from the visitor's browser.
 */
const DEV_API_URL = "http://localhost:8100";

export const API_URL = (process.env.NEXT_PUBLIC_API_URL || (process.env.NODE_ENV === "production" ? "" : DEV_API_URL)).trim().replace(/\/+$/, "");
export const API_CONFIGURED = API_URL !== "";

const NOT_CONFIGURED = "This deployment is not connected to the OceanSight API (NEXT_PUBLIC_API_URL is not set), so only saved copies of the reference views are available.";

const UNREACHABLE = "The OceanSight API is temporarily unavailable, and there is no saved copy of this view. Try again in a moment.";

if (!API_CONFIGURED && typeof window !== "undefined") {
  console.error("[OceanSight] NEXT_PUBLIC_API_URL is not set for this production build. Set it to the deployed FastAPI URL and redeploy.");
}

/** Absolute backend URL for links and downloads, or null when this build has no API configured. */
export function apiUrl(path: string): string | null {
  return API_CONFIGURED ? `${API_URL}${path}` : null;
}

export class ApiError extends Error {
  constructor(public status: number, public code: string, public detail: string) {
    super(detail);
  }
}

export type Fetched<T> = T & { __fallback?: boolean };

function flatten(obj: unknown, prefix = ""): string[] {
  if (obj === null || typeof obj !== "object") return [`${prefix}_${String(obj)}`];
  return Object.keys(obj as Record<string, unknown>)
    .sort()
    .flatMap((k) => flatten((obj as Record<string, unknown>)[k], prefix ? `${prefix}_${k}` : k));
}

export function fallbackKey(pathWithQuery: string, body?: unknown): string {
  let key = pathWithQuery.replace(/^\//, "");
  if (body !== undefined) key += "__" + flatten(body).join("_");
  return key.replace(/[^A-Za-z0-9._-]/g, "_");
}

async function tryFallback<T>(path: string, body?: unknown): Promise<Fetched<T> | null> {
  try {
    const r = await fetch(`/fallback/${fallbackKey(path, body)}.json`);
    if (!r.ok) return null;
    const data = (await r.json()) as T;
    return Object.assign(data as object, { __fallback: true }) as Fetched<T>;
  } catch {
    return null;
  }
}

async function request<T>(path: string, init?: RequestInit & { json?: unknown }, timeoutMs = 20000): Promise<Fetched<T>> {
  if (!API_CONFIGURED) {
    const fb = await tryFallback<T>(path, init?.json);
    if (fb) return fb;
    throw new ApiError(0, "api_not_configured", NOT_CONFIGURED);
  }
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  let res: Response;
  try {
    res = await fetch(`${API_URL}${path}`, {
      ...init,
      method: init?.json !== undefined ? "POST" : init?.method || "GET",
      headers: init?.json !== undefined ? { "Content-Type": "application/json" } : undefined,
      body: init?.json !== undefined ? JSON.stringify(init.json) : undefined,
      signal: ctrl.signal,
    });
  } catch {
    clearTimeout(timer);
    const fb = await tryFallback<T>(path, init?.json);
    if (fb) return fb;
    throw new ApiError(0, "backend_unreachable", UNREACHABLE);
  }
  clearTimeout(timer);
  if (!res.ok) {
    let code = "http_error";
    let detail = `HTTP ${res.status}`;
    try {
      const j = await res.json();
      code = j.error || code;
      detail = j.detail || detail;
    } catch {}
    // An untyped 502/503/504 comes from the host's gateway (backend restarting or asleep), not from the API:
    // treat it like an unreachable backend instead of showing a bare "HTTP 502".
    if (code === "http_error" && [502, 503, 504].includes(res.status)) {
      const fb = await tryFallback<T>(path, init?.json);
      if (fb) return fb;
      throw new ApiError(res.status, "backend_unreachable", UNREACHABLE);
    }
    throw new ApiError(res.status, code, detail);
  }
  return (await res.json()) as Fetched<T>;
}

export const get = <T,>(path: string) => request<T>(path);
export const post = <T,>(path: string, json: unknown) => request<T>(path, { json });

/** Human, calm messages per error code (docs/12 error states, docs/21 §2). */
export function friendlyError(e: unknown): string {
  if (!(e instanceof ApiError)) return "Something went wrong loading this view.";
  switch (e.code) {
    case "on_land":
    case "out_of_domain":
      return "This point is on land or outside the study domain (5–30°N, 45–105°E).";
    case "date_out_of_range":
      return `No reconstruction for that date. ${e.detail}`;
    case "database_unavailable":
      return "The metadata database is temporarily unavailable — map and profiles still work.";
    case "data_unavailable":
    case "validation_unavailable":
    case "embedding_unavailable":
      return "This product has not been computed yet on the server.";
    case "region_too_large":
      return "Region too large — try a smaller area.";
    case "no_ocean_cells":
      return "The selected box contains no ocean cells.";
    case "insufficient_forecast_history":
      return `A short-horizon estimate needs more reconstructed history before this day. ${e.detail}`;
    case "optional_dataset_unavailable":
      return e.detail;
    case "backend_unreachable":
    case "api_not_configured":
      return e.detail;
    case "internal_error":
      return "The OceanSight API reported an unexpected error. Try again in a moment.";
    default:
      return e.detail || "Unexpected error.";
  }
}

// ---------------------------------------------------------------- response types
export interface Meta {
  product: string;
  tagline?: string;
  domain: { min_lat: number; max_lat: number; min_lon: number; max_lon: number; resolution_deg: number };
  depths_m: number[];
  period: { start: string; end: string; n_days: number };
  splits: { train_years: number[]; val_years: number[]; test_years: number[] };
  production_model: string;
  models: Array<Record<string, unknown> & { name: string; architecture: string }>;
  available_models: string[];
  input_sources: Record<string, Record<string, string>>;
  target_source: Record<string, string>;
  data_label: string;
  /** Which layers / analyses this deployment can serve (absent on older API versions). */
  layers?: Record<LayerKey, LayerAvailability>;
  optional_sources?: Record<string, { status: string; enables: string; variables: string }>;
}

export type LayerKey = "temp" | "anomaly" | "uncertainty" | "tchp" | "mld" | "d20" | "d26" | "sss" | "sla" | "wind" | "salinity_subsurface" | "argo_salinity";
export interface LayerAvailability {
  status: "available" | "unavailable" | "not_configured" | "not_precomputed" | "database";
  detail: string;
}

/** Provenance classification used consistently across OceanSight (backend app/schemas.py). */
export type Classification = "measured" | "satellite" | "reanalysis" | "reconstructed" | "derived" | "estimated" | "forecast" | "baseline";
export interface ProvenanceInfo {
  classification: Classification;
  source: string;
  dataset?: string | null;
  model_version?: string | null;
  method?: string | null;
  note?: string | null;
  lineage_id?: string | null;
}

export interface GridResponse {
  date: string;
  requested_date: string;
  depth_m?: number | null;
  variable?: string;
  product?: string;
  classification?: Classification;
  provenance?: ProvenanceInfo;
  units: string;
  grid: { lat: number[]; lon: number[]; values: (number | null)[][] };
  stats: { min: number; max: number; mean: number } | null;
  source: string;
  data_label: string;
  model_version: string;
  notice: string | null;
}

export interface ArgoFloatRef {
  id: number;
  platform_number: string;
  cycle_number: number;
  profile_date: string;
  lat: number;
  lon: number;
  distance_km: number;
  date_offset_days: number;
  split: string;
  independent: boolean;
  temperature_c_std_depths: (number | null)[];
}

export interface Derived {
  mld_m: number | null;
  d20_m: number | null;
  d26_m: number | null;
  tchp_kj_cm2: number | null;
}

export interface ProfileResponse {
  date: string;
  requested_date: string;
  lat: number;
  lon: number;
  cell: { lat: number; lon: number };
  depths_m: number[];
  temperature_c: (number | null)[];
  uncertainty_c: (number | null)[] | null;
  baseline_climatology_c: (number | null)[];
  comparisons: Record<string, (number | null)[]>;
  target_product_c: (number | null)[] | null;
  derived: Derived;
  nearest_argo_float: ArgoFloatRef | null;
  argo_lookup: string;
  data_label: string;
  model_version: string;
  notice: string | null;
}

export interface Headline {
  study_period: string;
  n_days_reconstructed: number;
  n_argo_profiles_total: number | null;
  target_days: number | null;
  n_models_compared: number;
  grid: string;
  production_model: string;
  validation: {
    held_out_period: string;
    n_independent_profiles: number;
    at_depths: { depth_m: number; rmse_c: number | null; climatology_rmse_c: number | null; n_obs: number | null }[];
    caveat: string;
  } | null;
}

export interface RegionStats {
  date: string;
  n_ocean_cells: number;
  mean_tchp_kj_cm2: number | null;
  max_tchp_kj_cm2: number | null;
  mean_mld_m: number | null;
  mean_d20_m: number | null;
  mean_d26_m: number | null;
  frac_cells_tchp_gt_50: number | null;
  mean_sst_c: number | null;
  mean_profile_c: (number | null)[];
  barrier_layer_flag: boolean | null;
  barrier_layer_proxy: { frac_cells_sss_below_threshold: number | null; sss_threshold_psu: number; note: string };
  notice: string | null;
}

export interface BBox {
  min_lat: number;
  max_lat: number;
  min_lon: number;
  max_lon: number;
}

export interface Region {
  name: string;
  bbox: BBox;
}

export interface DepthMetric {
  depth_m: number;
  n_obs: number;
  rmse_c?: number;
  bias_c?: number;
  corr?: number | null;
  clim_rmse_c?: number;
  skill_vs_climatology?: number;
  baseline_rmse_c?: number | null;
  lightgbm_rmse_c?: number | null;
  nosss_rmse_c?: number | null;
  target_product_rmse_c?: number | null;
}

export interface ValidationSummary {
  model: string;
  split: string;
  independent: boolean;
  held_out_period: string;
  n_profiles: number;
  per_depth: DepthMetric[];
  overall: Record<string, { mean_rmse_c: number | null; mean_bias_c: number | null; n_obs: number }>;
  uncertainty_calibration: {
    frac_within_1sigma: number | null;
    frac_within_2sigma: number | null;
    calibrated: { frac_within_1sigma?: number; frac_within_2sigma?: number; fit_on: string; note?: string } | null;
  };
  caveat: string;
  source: string;
}

export interface CycloneTrack {
  id: number;
  sid: string;
  name: string;
  season: number;
  peak_category: string | null;
  start: string | null;
  end: string | null;
  points: { time: string; lat: number; lon: number; category: string | null; grade: string | null; wind_kt: number | null }[];
}

export interface FuelResponse {
  id: number;
  name: string;
  season: number;
  peak_category: string | null;
  lead_days: number;
  points: {
    time: string;
    lat: number;
    lon: number;
    category: string | null;
    wind_kt: number | null;
    tchp_kj_cm2: number | null;
    d26_m: number | null;
    sst_c: number | null;
    ocean_date: string | null;
  }[];
  max_tchp_kj_cm2: number | null;
  note: string;
}

export interface ArgoMarker {
  id: number;
  platform_number: string;
  cycle_number: number;
  profile_date: string;
  lat: number;
  lon: number;
  split: string;
  independent: boolean;
  rmse_c: number | null;
}

export interface SectionResponse {
  date: string;
  lat: number;
  lon: number[];
  depths_m: number[];
  temperature_c: (number | null)[][];
  model_version: string;
  data_label: string;
}

/** GET /v1/section/{day} with orientation/variable (interactive vertical section). */
export interface SectionAnyResponse {
  date: string;
  requested_date: string;
  orientation: "zonal" | "meridional";
  variable: "temp" | "anomaly" | "uncertainty";
  units: string;
  x: number[];
  x_name: "lon" | "lat";
  depths_m: number[];
  values: (number | null)[][];
  lat: number | number[];
  lon: number | number[];
  model_version: string;
  data_label: string;
  notice: string | null;
}

/** GET /v1/timeline — reconstructed column at one cell through time (+ derived MLD/D20/D26). */
export interface TimelineResponse {
  lat: number;
  lon: number;
  cell: { lat: number; lon: number };
  start: string;
  end: string;
  requested_start: string;
  requested_end: string;
  stride_days: number;
  dates: string[];
  depths_m: number[];
  temperature_c: (number | null)[][]; // [depth][time]
  climatology_c: (number | null)[][] | null;
  mld_m: (number | null)[];
  d20_m: (number | null)[];
  d26_m: (number | null)[];
  max_samples: number;
  model_version: string;
  data_label: string;
  notice: string | null;
}

// ---------------------------------------------------------------- analysis & data workspaces
export type Quality = "good" | "limited" | "insufficient";

export interface GradientLayer {
  top_m: number;
  bottom_m: number;
  depth_m: number;
  gradient: number;
}

export interface GradientPeak {
  variable: string;
  depth_m: number | null;
  depth_range_m: [number, number] | null;
  gradient_per_m: number | null;
  strength_per_m: number | null;
  quality: Quality;
  quality_reasons: string[];
  n_levels_used: number;
  analysis_range_m: [number, number];
  gradient_profile: GradientLayer[];
  method: string;
  sense?: string | null;
}

export interface ArgoRef {
  id: number | null;
  platform_number: string;
  cycle_number: number;
  profile_date: string;
  lat: number;
  lon: number;
  distance_km: number;
  date_offset_days: number;
  split: string;
  independent: boolean;
  data_mode?: string | null;
}

export interface MixedLayers {
  mld_density_m: number | null;
  isothermal_layer_depth_m: number | null;
  barrier_layer_thickness_m: number | null;
  method: string;
}

export interface SourceStatus {
  status: "available" | "none_nearby" | "no_salinity" | "lookup_unavailable" | "not_configured" | "not_precomputed" | "no_data";
  detail: string;
}

export interface StratificationResponse {
  date: string;
  requested_date: string;
  lat: number;
  lon: number;
  cell: { lat: number; lon: number };
  max_depth_m: number;
  notice: string | null;
  reconstructed: {
    depths_m: number[];
    temperature_c: (number | null)[];
    uncertainty_c: (number | null)[] | null;
    thermocline: GradientPeak;
    mld_m: number | null;
    d20_m: number | null;
    d26_m: number | null;
    provenance: ProvenanceInfo;
  };
  observed: {
    argo: ArgoRef;
    bin_m: number;
    depths_m: number[];
    temperature_c: (number | null)[];
    salinity_psu: (number | null)[] | null;
    thermocline: GradientPeak | null;
    halocline: GradientPeak | null;
    mixed_layers: MixedLayers | null;
    qc: Record<string, { n_input: number; n_failed_range: number; n_failed_spike: number }>;
    provenance: ProvenanceInfo;
  } | null;
  observed_status: SourceStatus;
  reanalysis_salinity: {
    date: string;
    depths_m: number[];
    salinity_psu: (number | null)[];
    potential_temperature_c: (number | null)[];
    halocline: GradientPeak;
    provenance: ProvenanceInfo;
  } | null;
  reanalysis_status: SourceStatus;
  diagnostics: Record<string, string>;
}

export interface TSPoint {
  depth_m: number;
  temperature_c: number;
  salinity_psu: number;
  potential_temperature_c: number;
  sigma0_kg_m3: number;
}

export interface TSSeries {
  label: string;
  date: string;
  points: TSPoint[];
  argo?: ArgoRef | null;
  mixed_layers?: MixedLayers | null;
  provenance: ProvenanceInfo;
}

export interface TSProfileResponse {
  date: string;
  lat: number;
  lon: number;
  observed: TSSeries | null;
  observed_status: SourceStatus;
  reanalysis: TSSeries | null;
  reanalysis_status: SourceStatus;
  isopycnals: { sigma0: number; points: [number, number][] }[];
  axes: Record<string, string>;
  reconstructed_note: string;
  method: string;
}

export interface ForecastHorizon {
  horizon_days: number;
  target_date: string;
  temperature_c: (number | null)[];
  uncertainty_c: (number | null)[];
  method_rmse_c: (number | null)[];
  persistence_c: (number | null)[];
  persistence_rmse_c: (number | null)[];
  n_hindcast_pairs: number;
  verification_c: (number | null)[] | null;
}

export interface ForecastResponse {
  issue_date: string;
  requested_date: string;
  lat: number;
  lon: number;
  cell: { lat: number; lon: number };
  depths_m: number[];
  method: "trend" | "persistence";
  method_label: string;
  window_days: number;
  input_period: { start: string; end: string; n_days: number };
  hindcast_days: number;
  issue_temperature_c: (number | null)[];
  reconstruction_uncertainty_c: (number | null)[] | null;
  horizons: ForecastHorizon[];
  limitations: string[];
  notice: string | null;
  provenance: ProvenanceInfo;
}

export interface VolumeSampleResponse {
  date: string;
  requested_date: string;
  variable: "temp" | "anomaly" | "uncertainty";
  units: string;
  bbox: BBox;
  depths_m: number[];
  stride: number;
  max_points: number;
  n_points: number;
  lat: number[];
  lon: number[];
  depth: number[];
  value: number[];
  stats: { min: number; max: number; mean: number } | null;
  notice: string | null;
  provenance: ProvenanceInfo;
}

export interface WindVectorsResponse {
  date: string;
  stride: number;
  vectors: { lat: number; lon: number; u_ms: number; v_ms: number; speed_ms: number; direction_from_deg: number }[];
  direction_convention: string;
  notice: string | null;
  provenance: ProvenanceInfo;
}

export interface DataQualityResponse {
  datasets: { id: string; name: string; classification: Classification; status: Quality | null; status_reason: string; metrics: Record<string, unknown> }[];
  inputs: {
    variable: string;
    source: string | null;
    n_ocean_values: number | null;
    missing_before_fill: number | null;
    missing_before_fill_pct: number | null;
    filled_temporal: number | null;
    filled_spatial: number | null;
    filled_pct: number | null;
    invalid_flagged: number | null;
    duplicate_times: number | null;
    days_absent_in_source: number | null;
    valid_range: (number | null)[];
    status: Quality;
    status_reason: string;
  }[];
  argo: null | {
    n_profiles: number | null;
    detail_available: boolean;
    note?: string;
    split_counts?: Record<string, number>;
    data_mode_counts?: Record<string, number>;
    temporal?: { first: string | null; last: string | null; per_month: { month: string; n: number }[] };
    spatial?: { ocean_boxes_1deg: number; boxes_with_profiles: number; coverage_pct: number | null; test_year_coverage_pct: number | null };
    depth?: { per_standard_depth: { depth_m: number; n_valid: number; coverage_pct: number | null; status: Quality | null }[]; profiles_reaching_500m_pct: number | null; profiles_reaching_1000m_pct: number | null };
    salinity?: { profiles_with_salinity: number; profiles_with_salinity_pct: number | null; valid_salinity_levels_pct: number | null; note: string };
    independent_profiles?: number;
    independent_status?: Quality | null;
    qc_record: Record<string, unknown> | null;
    rejected_note?: string | null;
  };
  thresholds: Record<string, { meaning: string; good_max?: number; limited_max?: number; good_min?: number; limited_min?: number }>;
  qc_rules: { step: string; rule: string; applies_to: string }[];
  files: string[];
}

export interface LineageRow {
  id: string;
  variable: string;
  classification: Classification;
  provider: string;
  dataset: string;
  url: string;
  native_resolution: string;
  recorded: boolean;
  resolution: string;
  temporal_coverage: string;
  depth_coverage: string;
  processing: string[] | string;
  role: string;
  availability: { status: string; detail: string };
  lineage: { stage: string; detail: string }[];
  shown_in: string[];
}

export interface LineageResponse {
  classifications: Record<Classification, string>;
  variables: LineageRow[];
  optional_sources: Record<string, Record<string, string>>;
  model_version: string | null;
}
